---
title: Services
subtitle: >
  I specialize in locomotion flow, bodyweight strength, and handstands.

description: >
  My coaching services include one-on-one sessions, group classes, and online programming to guide you along your movement journey.

order: 2
---


## Online Coaching for GMB Programs

For this option, I will provide personalized feedback and answer all your questions while you follow one or more GMB program. This may include calls, online check-ins, and program modification. Note that you will have to purchase the program separately.

<a class="flux-button _3" href="https://gmb.io/programs/">GMB Programs</a>

## Individual and Group Training

In these sessions, I guide you or a group of friends through a workout online or in person to help you move towards your fitness goals.

We can focus on a specific skill like handstands  🙃 or general goals like strength and flexibility.

## Custom Service

Looking for something different?

Maybe a private handstand class for your bachelorette weekend? Or a team-building flexibility workshop for your cohort?

Please, share your ideas! I am all ears 🐰​

Let's discuss your needs and come up with something just for you. ​ Send me an email to set up a free consultation.